import type { BuiltInMcqRow } from "@/lib/physicsChapter2Mcqs";

// Built-in fallback so Section 2 is visible before the database seed is applied.
const SECTION_2: Array<readonly [string, readonly string[], number]> = [
  ["Why doesn’t Mr Darcy want to dance?", ["He does not like the women in the room", "He knows his partner too well", "He is engaged to Mr Bingley’s sister", "He does not know how to dance"], 0],
  ["Who does Mr Darcy think is the only beautiful girl in the room?", ["Elizabeth", "Lydia", "Jane", "Charlotte"], 2],
  ["How does Elizabeth react to Mr Darcy’s comment?", ["She feels ridiculous", "She finds it funny", "She finds it very friendly", "She becomes angry"], 1],
  ["What did Mrs Bennet think of Mr Bingley?", ["She was curious", "She was delighted", "She was disappointed", "She was frightened"], 1],
  ["What did Mrs Bennet think of Mr Darcy?", ["She thought he was not handsome", "She thought he was great", "She thought he was too proud", "She thought he was lively"], 2],
  ["Which statement about Mr Bingley’s sisters is correct?", ["Both of them have husbands", "Neither of them has a husband", "Only Louisa Hurst is presented as married", "Caroline Bingley is married to Mr Darcy"], 2],
  ["What does Mr Bingley think about Mr Darcy?", ["He is too difficult to please", "He is lively and playful", "He is very easy to please", "He enjoys every ball"], 0],
  ["What does Mr Bingley think about Elizabeth?", ["She is proud", "She is pretty", "She is rude", "She is difficult to please"], 1],
  ["Which statement about Mr Darcy’s opinion is false?", ["He thinks Jane is beautiful", "He thinks Jane is the only beautiful girl in the room", "He thinks Elizabeth is the only beautiful girl in the room", "He does not admire the other women in the room"], 2],
  ["Which description of Mr Darcy did Elizabeth not agree with?", ["Lively and playful", "Proud", "Difficult to please", "Cold"], 0],
  ["Which statement about Mr Bingley’s dancing is correct?", ["He danced with all the girls twice", "He danced with Jane twice", "He refused to dance with Jane", "He did not attend the ball"], 1],
  ["Which statement about Mrs Bennet’s opinion of Mr Darcy is false?", ["She thought he was too proud", "She did not think he was great", "She thought he was so great", "She disliked his proud behaviour"], 2],
  ["What does “a good number of” mean?", ["One", "Several", "None", "A couple"], 1],
  ["Which word means “to help two people meet”?", ["Admire", "Introduce", "Refuse", "Attend"], 1],
  ["Which word means “in a rude and not very warm way”?", ["Lively", "Coldly", "Elegantly", "Regularly"], 1],
  ["Which word means “full of energy”?", ["Lively", "Muddy", "Proud", "Jealous"], 0],
  ["Which word means “wanted or liked”?", ["Introduced", "Admired", "Refused", "Discussed"], 1],
  ["What does “fancy” mean in the extract?", ["Difficult", "Elegant", "Muddy", "Playful"], 1],
  ["Which word means “dress”?", ["Gown", "Estate", "Ball", "Storm"], 0],
  ["Who danced with Jane twice?", ["Mr Darcy", "Mr Bennet", "Mr Bingley", "Sir Lucas"], 2],
  ["Who did not attend the ball?", ["Mr Bennet", "Mr Bingley", "Mr Darcy", "Sir Lucas"], 0],
  ["Who thought the ball was a waste of time?", ["Elizabeth", "Mrs Bennet", "Mr Darcy", "Mr Bingley"], 2],
  ["Who was interested in the women’s dresses?", ["Elizabeth", "Jane", "Charlotte", "Mrs Bennet"], 3],
  ["Who laughed with her friends about Mr Darcy?", ["Caroline Bingley", "Elizabeth", "Louisa Hurst", "Jane"], 1],
  ["What is the relationship between the Lucas family and the Bennet family?", ["They are relatives", "They are neighbours", "They are enemies", "They are business partners"], 1],
  ["Who is the eldest daughter of the Lucas family?", ["Jane", "Elizabeth", "Caroline", "Charlotte"], 3],
  ["Who is Elizabeth’s best friend?", ["Louisa Hurst", "Caroline Bingley", "Charlotte Lucas", "Mrs Bennet"], 2],
  ["Who are Mr Bingley’s sisters?", ["Jane and Elizabeth", "Caroline Bingley and Louisa Hurst", "Charlotte and Lydia", "Elizabeth and Caroline"], 1],
  ["Who is Louisa Hurst’s husband?", ["Mr Darcy", "Mr Bennet", "Mr Hurst", "Sir Lucas"], 2],
  ["Why is Louisa called Mrs Louisa Hurst?", ["Hurst is her father’s surname", "Hurst is her husband’s surname", "Hurst is the name of her estate", "Hurst is her brother’s name"], 1],
  ["When do the Bennets discuss the events of the ball with the Lucases?", ["During the ball", "The evening before the ball", "The morning after the ball", "One week after the ball"], 2],
  ["With whom do the Bennets discuss the events of the ball?", ["The Hursts", "The Lucases", "The Darcys", "The Bingleys"], 1],
  ["Who points out that Mr Bingley thought Jane was the prettiest girl at the ball?", ["Mrs Bennet", "Caroline Bingley", "Charlotte Lucas", "Elizabeth"], 2],
  ["With whom did Charlotte dance before Mr Bingley danced with Jane?", ["Mr Darcy", "Sir Lucas", "Mr Hurst", "Mr Bingley"], 3],
  ["Who did Mr Bingley think was the prettiest girl at the ball?", ["Elizabeth", "Charlotte", "Jane", "Caroline"], 2],
  ["Between whom does a romance begin to develop?", ["Mr Darcy and Caroline", "Mr Bingley and Jane", "Mr Hurst and Elizabeth", "Sir Lucas and Mrs Bennet"], 1],
  ["Who begins to see the Bennets regularly?", ["Mr Bingley, his sisters and Mr Darcy", "Mr Hurst alone", "Sir Lucas and Charlotte only", "Caroline Bingley alone"], 0],
  ["Toward whom does Mr Darcy begin to form an interest?", ["Jane", "Charlotte", "Caroline", "Elizabeth"], 3],
  ["What does Mr Darcy begin to do as his interest in Elizabeth develops?", ["Avoid her completely", "Pay more and more attention to her", "Ask her to leave the estate", "Speak only to Jane"], 1],
  ["Where does Sir Lucas suggest that Elizabeth and Mr Darcy dance together?", ["At the Bennets’ house", "At Netherfield", "At a ball in the Lucases’ house", "At Mr Hurst’s house"], 2],
  ["Who suggests that Elizabeth and Mr Darcy dance together?", ["Mr Bingley", "Sir Lucas", "Mr Bennet", "Mr Hurst"], 1],
  ["How does Elizabeth respond to the suggestion that she dance with Mr Darcy?", ["She accepts immediately", "She asks Jane to dance instead", "She refuses", "She leaves the ball"], 2],
  ["What does Elizabeth’s refusal surprisingly lead Mr Darcy to do?", ["Leave the Lucas house", "Tell Caroline that he is falling for Elizabeth", "Stop visiting the Bennets", "Become interested in Jane"], 1],
  ["To whom does Mr Darcy say that he is falling for Elizabeth?", ["Jane", "Charlotte", "Caroline", "Mrs Bennet"], 2],
  ["How does Caroline react to Mr Darcy’s growing feelings for Elizabeth?", ["She becomes delighted", "She becomes jealous", "She becomes ill", "She becomes playful"], 1],
  ["Where does Jane get caught in a storm?", ["During a visit to Netherfield", "At the Lucases’ house", "At the Bennets’ house", "At the first ball"], 0],
  ["What happens to Jane after she is caught in the storm?", ["She gets lost", "She falls ill", "She returns home immediately", "She refuses to see Mr Bingley"], 1],
  ["Where does Jane have to stay while recovering?", ["In the Lucas household", "In the Bennet household", "In the Bingley household", "In the Hurst household"], 2],
  ["What does Elizabeth do when she hears that Jane is ill?", ["She sends Mr Darcy to visit her", "She walks the whole way to the estate", "She waits for Jane to return", "She attends another ball"], 1],
  ["In what condition does Elizabeth arrive at the estate?", ["In an elegant gown", "In a muddy dress", "In a wet coat", "In a new dress"], 1],
  ["Who is surprised by Elizabeth’s arrival in a muddy dress?", ["Only Jane", "Only Mr Bingley", "The Bingleys, Mr and Mrs Hurst, and Mr Darcy", "The Bennets and the Lucases"], 2],
];

export const getBuiltInEnglishLiteratureSection2 = (language: "ar" | "en"): BuiltInMcqRow[] =>
  SECTION_2.map(([question, choices, answerIndex], index) => ({
    id: `builtin-english-literature-2-${language}-${String(index + 1).padStart(2, "0")}`,
    subject: "english_literature",
    chapter: 2,
    chapter_title: "Section 2",
    question,
    choices: [...choices],
    answer_index: answerIndex,
    explanation: null,
  }));
