import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { Eye, EyeOff, Hand, Layers3, Lock, Rotate3D } from "lucide-react";

type PointKey = "A" | "B" | "C";
type PlaneKey = "X" | "Y" | "Z";
type LineKey = "AB" | "AC";

type SceneVisibility = {
  planes: Record<PlaneKey, boolean>;
  lines: Record<LineKey, boolean>;
};

type GeometryState = {
  points: Record<PointKey, THREE.Vector3>;
  horizontal: THREE.Vector3;
  axisAB: THREE.Vector3;
  candidateAxis: THREE.Vector3;
  constructedPlane: THREE.Vector3[];
  candidatePlane: THREE.Vector3[];
  candidateAngleWithX: number;
  distanceCToCandidate: number;
};

const THEOREM = "من مستقيم غير عمودي على مستوى معلوم يوجد مستوى وحيد عمودي على المستوى المعلوم.";

const PROOF_STEPS = [
  "من النقطة A الواقعة على المستقيم AB نرسم AC ⟂ المستوى X.",
  "المستقيمان AB وAC متقاطعان في A؛ لذلك يحددان مستوى وحيداً نسميه Y.",
  "المستوى Y يحتوي المستقيم AC العمودي على X؛ إذن Y ⟂ X. وبذلك ثبت وجود المستوى المطلوب.",
  "لبرهنة الوحدانية، نفترض وجود مستوى آخر Z يحتوي AB ويكون Z ⟂ X.",
  "بما أن Z يمر بالنقطة A ويعامد X، فإنه يحتوي العمود الوحيد AC المرسوم من A على X.",
  "المستويان Y وZ يحتويان المستقيمين المتقاطعين AB وAC؛ لذلك Z = Y. إذن المستوى موجود ووحيد، وهو المطلوب إثباته.",
] as const;

const radians = (degrees: number) => (degrees * Math.PI) / 180;

function rectanglePoints(
  center: THREE.Vector3,
  firstAxis: THREE.Vector3,
  secondAxis: THREE.Vector3,
  firstHalf: number,
  secondHalf: number,
) {
  return [
    center.clone().addScaledVector(firstAxis, -firstHalf).addScaledVector(secondAxis, -secondHalf),
    center.clone().addScaledVector(firstAxis, firstHalf).addScaledVector(secondAxis, -secondHalf),
    center.clone().addScaledVector(firstAxis, firstHalf).addScaledVector(secondAxis, secondHalf),
    center.clone().addScaledVector(firstAxis, -firstHalf).addScaledVector(secondAxis, secondHalf),
  ];
}

function planeGeometry(points: THREE.Vector3[]) {
  const geometry = new THREE.BufferGeometry();
  const vertices = [points[0], points[1], points[2], points[0], points[2], points[3]]
    .flatMap((point) => [point.x, point.y, point.z]);
  geometry.setAttribute("position", new THREE.Float32BufferAttribute(vertices, 3));
  geometry.computeVertexNormals();
  return geometry;
}

function borderGeometry(points: THREE.Vector3[]) {
  return new THREE.BufferGeometry().setFromPoints([...points, points[0]]);
}

/**
 * X is horizontal. AB is deliberately non-perpendicular to X.
 * Y is generated by AB and the unique perpendicular AC. Z pivots around AB,
 * letting the student test whether any different plane can also be perpendicular.
 */
function calculateGeometry(lineDirection: number, candidateRotation: number): GeometryState {
  const vertical = new THREE.Vector3(0, 1, 0);
  const bearing = radians(lineDirection);
  const horizontal = new THREE.Vector3(-Math.cos(bearing), 0, -Math.sin(bearing)).normalize();
  const A = new THREE.Vector3(0, 1.9, 0);
  const B = A.clone().addScaledVector(horizontal, 1.95).addScaledVector(vertical, -0.75);
  const C = new THREE.Vector3(0, 0, 0);
  const axisAB = B.clone().sub(A).normalize();
  const directionAC = C.clone().sub(A).normalize();
  const perpendicularWithinY = directionAC
    .clone()
    .addScaledVector(axisAB, -directionAC.dot(axisAB))
    .normalize();
  const candidateAxis = perpendicularWithinY
    .clone()
    .applyAxisAngle(axisAB, radians(candidateRotation))
    .normalize();

  const constructedCenter = A.clone().addScaledVector(horizontal, 0.2).addScaledVector(vertical, -0.85);
  const candidateCenter = A.clone().add(B).multiplyScalar(0.5);
  const constructedPlane = rectanglePoints(constructedCenter, horizontal, vertical, 2.4, 1.35);
  const candidatePlane = rectanglePoints(candidateCenter, axisAB, candidateAxis, 2.35, 2.0);

  const candidateNormal = axisAB.clone().cross(candidateAxis).normalize();
  const dot = THREE.MathUtils.clamp(Math.abs(candidateNormal.dot(vertical)), 0, 1);
  const candidateAngleWithX = Math.acos(dot) * 180 / Math.PI;
  const distanceCToCandidate = Math.abs(candidateNormal.dot(C.clone().sub(A)));

  return {
    points: { A, B, C },
    horizontal,
    axisAB,
    candidateAxis,
    constructedPlane,
    candidatePlane,
    candidateAngleWithX,
    distanceCToCandidate,
  };
}

function makeLabel(text: string, color: string, width = 256) {
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = 128;
  const context = canvas.getContext("2d")!;
  context.fillStyle = "rgba(255,255,255,0.95)";
  context.beginPath();
  context.roundRect(12, 24, width - 24, 80, 20);
  context.fill();
  context.fillStyle = color;
  context.font = "bold 54px Cairo, sans-serif";
  context.textAlign = "center";
  context.textBaseline = "middle";
  context.fillText(text, width / 2, 66, width - 36);
  const texture = new THREE.CanvasTexture(canvas);
  const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: texture, transparent: true, depthTest: false }));
  sprite.scale.set(width === 384 ? 0.95 : 0.63, 0.315, 1);
  sprite.renderOrder = 15;
  return sprite;
}

type SceneUpdate = (lineDirection: number, candidateRotation: number) => void;
type VisibilityUpdate = (visibility: SceneVisibility) => void;
type InteractionUpdate = (enabled: boolean) => void;

export default function UniquePerpendicularPlaneVisualizer() {
  const mountRef = useRef<HTMLDivElement>(null);
  const updateRef = useRef<SceneUpdate | null>(null);
  const visibilityRef = useRef<VisibilityUpdate | null>(null);
  const interactionRef = useRef<InteractionUpdate | null>(null);
  const [lineDirection, setLineDirection] = useState(28);
  const [candidateRotation, setCandidateRotation] = useState(35);
  const [activeStep, setActiveStep] = useState(-1);
  const [interactionEnabled, setInteractionEnabled] = useState(false);
  const [visibilityOpen, setVisibilityOpen] = useState(false);
  const [sceneError, setSceneError] = useState(false);
  const [planeVisibility, setPlaneVisibility] = useState<Record<PlaneKey, boolean>>({ X: true, Y: true, Z: true });
  const [lineVisibility, setLineVisibility] = useState<Record<LineKey, boolean>>({ AB: true, AC: true });
  const sceneVisibility = useMemo<SceneVisibility>(
    () => ({ planes: planeVisibility, lines: lineVisibility }),
    [planeVisibility, lineVisibility],
  );

  useEffect(() => {
    const mount = mountRef.current;
    if (!mount) return;

    const scene = new THREE.Scene();
    scene.background = new THREE.Color("#fcfbf5");
    const camera = new THREE.PerspectiveCamera(43, 1, 0.1, 100);
    camera.position.set(4.8, 3.9, 5.8);

    let renderer: THREE.WebGLRenderer;
    try {
      renderer = new THREE.WebGLRenderer({ antialias: true });
    } catch {
      setSceneError(true);
      return;
    }
    renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
    renderer.domElement.style.display = "block";
    renderer.domElement.style.width = "100%";
    renderer.domElement.style.height = "100%";
    mount.appendChild(renderer.domElement);

    const controls = new OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.target.set(-0.35, 0.8, -0.15);
    controls.minDistance = 3;
    controls.maxDistance = 12;
    controls.update();
    const setInteraction: InteractionUpdate = (enabled) => {
      controls.enabled = enabled;
      renderer.domElement.style.pointerEvents = enabled ? "auto" : "none";
      controls.update();
    };
    interactionRef.current = setInteraction;
    setInteraction(interactionEnabled);

    const planeXPoints = [
      new THREE.Vector3(-2.7, 0, -2.1),
      new THREE.Vector3(2.7, 0, -2.1),
      new THREE.Vector3(2.7, 0, 2.1),
      new THREE.Vector3(-2.7, 0, 2.1),
    ];
    const planeX = new THREE.Mesh(
      planeGeometry(planeXPoints),
      new THREE.MeshBasicMaterial({ color: "#bfdbfe", side: THREE.DoubleSide, transparent: true, opacity: 0.3, depthWrite: false }),
    );
    const xBorder = new THREE.Line(
      borderGeometry(planeXPoints),
      new THREE.LineBasicMaterial({ color: "#2563eb", depthTest: false }),
    );
    planeX.renderOrder = 1;
    xBorder.renderOrder = 5;
    scene.add(planeX, xBorder);

    let latestGeometry = calculateGeometry(lineDirection, candidateRotation);
    const planeY = new THREE.Mesh(
      planeGeometry(latestGeometry.constructedPlane),
      new THREE.MeshBasicMaterial({ color: "#ef4444", side: THREE.DoubleSide, transparent: true, opacity: 0.2, depthWrite: false }),
    );
    const yBorder = new THREE.Line(
      borderGeometry(latestGeometry.constructedPlane),
      new THREE.LineBasicMaterial({ color: "#dc2626", depthTest: false }),
    );
    const planeZMaterial = new THREE.MeshBasicMaterial({ color: "#f59e0b", side: THREE.DoubleSide, transparent: true, opacity: 0.16, depthWrite: false });
    const zBorderMaterial = new THREE.LineBasicMaterial({ color: "#d97706", depthTest: false });
    const planeZ = new THREE.Mesh(planeGeometry(latestGeometry.candidatePlane), planeZMaterial);
    const zBorder = new THREE.Line(borderGeometry(latestGeometry.candidatePlane), zBorderMaterial);
    planeY.renderOrder = 2;
    planeZ.renderOrder = 3;
    yBorder.renderOrder = 6;
    zBorder.renderOrder = 7;
    scene.add(planeY, yBorder, planeZ, zBorder);

    const abLine = new THREE.Line(
      new THREE.BufferGeometry().setFromPoints([latestGeometry.points.A, latestGeometry.points.B]),
      new THREE.LineBasicMaterial({ color: "#dc2626", depthTest: false }),
    );
    const acLine = new THREE.Line(
      new THREE.BufferGeometry().setFromPoints([latestGeometry.points.A, latestGeometry.points.C]),
      new THREE.LineBasicMaterial({ color: "#16a34a", depthTest: false }),
    );
    abLine.renderOrder = 10;
    acLine.renderOrder = 10;
    scene.add(abLine, acLine);

    const rightAngle = new THREE.Line(
      new THREE.BufferGeometry(),
      new THREE.LineBasicMaterial({ color: "#16a34a", depthTest: false }),
    );
    rightAngle.renderOrder = 11;
    scene.add(rightAngle);

    const dots = new Map<PointKey, THREE.Mesh>();
    const labels = new Map<PointKey, THREE.Sprite>();
    for (const point of ["A", "B", "C"] as const) {
      const color = point === "C" ? "#166534" : "#172554";
      const dot = new THREE.Mesh(
        new THREE.SphereGeometry(0.055, 14, 10),
        new THREE.MeshBasicMaterial({ color, depthTest: false }),
      );
      dot.renderOrder = 12;
      const label = makeLabel(point, color);
      scene.add(dot, label);
      dots.set(point, dot);
      labels.set(point, label);
    }

    const xLabel = makeLabel("X", "#2563eb");
    const yLabel = makeLabel("Y", "#dc2626");
    const zLabel = makeLabel("Z", "#d97706");
    const sameLabel = makeLabel("Y = Z", "#15803d", 384);
    scene.add(xLabel, yLabel, zLabel, sameLabel);

    let latestVisibility = sceneVisibility;
    let planesCoincide = candidateRotation === 0;
    const applyVisibility: VisibilityUpdate = (visibility) => {
      latestVisibility = visibility;
      planeX.visible = visibility.planes.X;
      xBorder.visible = visibility.planes.X;
      xLabel.visible = visibility.planes.X;
      planeY.visible = visibility.planes.Y;
      yBorder.visible = visibility.planes.Y;
      planeZ.visible = visibility.planes.Z;
      zBorder.visible = visibility.planes.Z;
      yLabel.visible = visibility.planes.Y && !planesCoincide;
      zLabel.visible = visibility.planes.Z && !planesCoincide;
      sameLabel.visible = visibility.planes.Y && visibility.planes.Z && planesCoincide;
      abLine.visible = visibility.lines.AB;
      acLine.visible = visibility.lines.AC;
      rightAngle.visible = visibility.lines.AC && visibility.planes.X;
      dots.get("A")!.visible = visibility.lines.AB || visibility.lines.AC;
      labels.get("A")!.visible = visibility.lines.AB || visibility.lines.AC;
      dots.get("B")!.visible = visibility.lines.AB;
      labels.get("B")!.visible = visibility.lines.AB;
      dots.get("C")!.visible = visibility.lines.AC;
      labels.get("C")!.visible = visibility.lines.AC;
    };
    visibilityRef.current = applyVisibility;

    const replacePlane = (mesh: THREE.Mesh, border: THREE.Line, points: THREE.Vector3[]) => {
      mesh.geometry.dispose();
      mesh.geometry = planeGeometry(points);
      border.geometry.dispose();
      border.geometry = borderGeometry(points);
    };

    const update: SceneUpdate = (direction, rotation) => {
      latestGeometry = calculateGeometry(direction, rotation);
      planesCoincide = rotation === 0;
      replacePlane(planeY, yBorder, latestGeometry.constructedPlane);
      replacePlane(planeZ, zBorder, latestGeometry.candidatePlane);

      abLine.geometry.dispose();
      abLine.geometry = new THREE.BufferGeometry().setFromPoints([latestGeometry.points.A, latestGeometry.points.B]);
      acLine.geometry.dispose();
      acLine.geometry = new THREE.BufferGeometry().setFromPoints([latestGeometry.points.A, latestGeometry.points.C]);

      const vertical = new THREE.Vector3(0, 1, 0);
      const c = latestGeometry.points.C;
      rightAngle.geometry.dispose();
      rightAngle.geometry = new THREE.BufferGeometry().setFromPoints([
        c.clone().addScaledVector(vertical, 0.27),
        c.clone().addScaledVector(vertical, 0.27).addScaledVector(latestGeometry.horizontal, 0.27),
        c.clone().addScaledVector(latestGeometry.horizontal, 0.27),
      ]);

      dots.get("A")!.position.copy(latestGeometry.points.A);
      dots.get("B")!.position.copy(latestGeometry.points.B);
      dots.get("C")!.position.copy(latestGeometry.points.C);
      labels.get("A")!.position.copy(latestGeometry.points.A).add(new THREE.Vector3(0.18, 0.2, 0));
      labels.get("B")!.position.copy(latestGeometry.points.B).add(new THREE.Vector3(-0.18, 0.2, 0));
      labels.get("C")!.position.copy(latestGeometry.points.C).add(new THREE.Vector3(0.2, 0.16, 0));

      xLabel.position.set(2.05, 0.12, -1.55);
      yLabel.position.copy(latestGeometry.points.A)
        .addScaledVector(latestGeometry.horizontal, -1.8)
        .add(new THREE.Vector3(0, -0.65, 0));
      const midpointAB = latestGeometry.points.A.clone().add(latestGeometry.points.B).multiplyScalar(0.5);
      zLabel.position.copy(midpointAB)
        .addScaledVector(latestGeometry.axisAB, 1.65)
        .addScaledVector(latestGeometry.candidateAxis, 1.35);
      sameLabel.position.copy(latestGeometry.points.A)
        .addScaledVector(latestGeometry.horizontal, -1.6)
        .add(new THREE.Vector3(0, -0.55, 0));

      planeZMaterial.color.set(planesCoincide ? "#22c55e" : "#f59e0b");
      zBorderMaterial.color.set(planesCoincide ? "#16a34a" : "#d97706");
      applyVisibility(latestVisibility);
    };
    updateRef.current = update;
    update(lineDirection, candidateRotation);

    const resize = (width: number, height: number) => {
      if (width < 2 || height < 2) return;
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
      renderer.setSize(Math.round(width), Math.round(height), false);
    };
    const observer = new ResizeObserver(([entry]) => {
      if (entry) resize(entry.contentRect.width, entry.contentRect.height);
    });
    observer.observe(mount);
    const initialRect = mount.getBoundingClientRect();
    resize(initialRect.width, initialRect.height);
    const handleWindowResize = () => {
      const rect = mount.getBoundingClientRect();
      resize(rect.width, rect.height);
    };
    window.addEventListener("resize", handleWindowResize);

    let frame = 0;
    const render = () => {
      frame = requestAnimationFrame(render);
      controls.update();
      renderer.render(scene, camera);
    };
    render();

    return () => {
      updateRef.current = null;
      visibilityRef.current = null;
      interactionRef.current = null;
      cancelAnimationFrame(frame);
      observer.disconnect();
      window.removeEventListener("resize", handleWindowResize);
      controls.dispose();
      scene.traverse((object) => {
        if (object instanceof THREE.Mesh || object instanceof THREE.Line || object instanceof THREE.Sprite) {
          if (object instanceof THREE.Mesh || object instanceof THREE.Line) object.geometry.dispose();
          const material = object.material as THREE.Material;
          if (material instanceof THREE.SpriteMaterial) material.map?.dispose();
          material.dispose();
        }
      });
      renderer.dispose();
      renderer.domElement.remove();
    };
    // Scene objects are created once; controls update them through refs.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => { updateRef.current?.(lineDirection, candidateRotation); }, [lineDirection, candidateRotation]);
  useEffect(() => { visibilityRef.current?.(sceneVisibility); }, [sceneVisibility]);
  useEffect(() => { interactionRef.current?.(interactionEnabled); }, [interactionEnabled]);

  const geometry = calculateGeometry(lineDirection, candidateRotation);
  const uniquePlaneConfirmed = candidateRotation === 0;
  const chooseStep = (index: number) => {
    setActiveStep(index);
    if (index >= 3) setCandidateRotation(0);
  };
  const setAllVisible = (visible: boolean) => {
    setPlaneVisibility({ X: visible, Y: visible, Z: visible });
    setLineVisibility({ AB: visible, AC: visible });
  };

  return (
    <section dir="rtl" className="rounded-3xl border border-slate-200 bg-white p-4 text-slate-900 shadow-sm sm:p-6" style={{ fontFamily: "Cairo, Tajawal, sans-serif" }}>
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-black text-amber-600">المبرهنة 9</p>
          <h2 className="mt-1 text-xl font-extrabold text-[#183A72] sm:text-2xl">وجود ووحدانية المستوى العمودي</h2>
        </div>
        <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-[#183A72]">هندسة مجسمة</span>
      </div>
      <p className="mt-3 text-sm leading-8 sm:text-base">{THEOREM}</p>

      <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(270px,1fr)]">
        <div>
          <div className="relative">
            <div
              ref={mountRef}
              role="img"
              aria-label="المستقيم AB غير عمودي على المستوى X، والمستقيم AC عمودي على X، ويحددان المستوى العمودي الوحيد Y"
              className={`h-[340px] w-full overflow-hidden rounded-2xl border border-blue-100 bg-[#fcfbf5] sm:h-[440px] ${interactionEnabled ? "touch-none" : "touch-pan-y"}`}
            />

            {sceneError && (
              <div className="absolute inset-0 grid place-items-center rounded-2xl bg-[#fcfbf5] p-6 text-center">
                <div>
                  <Rotate3D className="mx-auto h-10 w-10 text-[#183A72]" />
                  <p className="mt-3 font-bold text-[#183A72]">تعذّر تشغيل العرض ثلاثي الأبعاد على هذا الجهاز.</p>
                  <p className="mt-1 text-sm text-slate-500">جرّب تفعيل تسريع الرسوميات في المتصفح أو افتح الصفحة من جهاز آخر.</p>
                </div>
              </div>
            )}

            <div className="absolute left-3 top-3 z-20 flex gap-2" dir="rtl">
              <button
                type="button"
                onClick={() => setInteractionEnabled((enabled) => !enabled)}
                aria-pressed={interactionEnabled}
                title={interactionEnabled ? "قفل تحريك المجسم" : "تفعيل تحريك المجسم"}
                className={`inline-flex h-11 items-center gap-2 rounded-xl border px-3 text-xs font-bold shadow-md backdrop-blur transition ${interactionEnabled ? "border-[#183A72] bg-[#183A72] text-white" : "border-slate-200 bg-white/95 text-slate-700 hover:bg-slate-50"}`}
              >
                {interactionEnabled ? <Lock className="h-4 w-4" /> : <Hand className="h-4 w-4" />}
                <span className="hidden sm:inline">{interactionEnabled ? "قفل العرض" : "حرّك المجسم"}</span>
              </button>
              <button
                type="button"
                onClick={() => setVisibilityOpen((open) => !open)}
                aria-expanded={visibilityOpen}
                title="إظهار وإخفاء المستويات والمستقيمات"
                className={`inline-flex h-11 items-center gap-2 rounded-xl border px-3 text-xs font-bold shadow-md backdrop-blur transition ${visibilityOpen ? "border-violet-600 bg-violet-600 text-white" : "border-slate-200 bg-white/95 text-slate-700 hover:bg-slate-50"}`}
              >
                <Layers3 className="h-4 w-4" />
                <span className="hidden sm:inline">العناصر</span>
              </button>
            </div>

            {visibilityOpen && (
              <div className="absolute left-3 top-16 z-20 w-64 max-w-[calc(100%-1.5rem)] rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-xl backdrop-blur" dir="rtl">
                <div className="mb-3 flex items-center justify-between gap-2">
                  <strong className="text-sm text-[#183A72]">إظهار وإخفاء العناصر</strong>
                  <div className="flex gap-1">
                    <button type="button" onClick={() => setAllVisible(true)} className="rounded-lg bg-slate-100 px-2 py-1 text-[11px] font-bold hover:bg-slate-200">الكل</button>
                    <button type="button" onClick={() => setAllVisible(false)} className="rounded-lg bg-slate-100 px-2 py-1 text-[11px] font-bold hover:bg-slate-200">إخفاء</button>
                  </div>
                </div>
                <div className="space-y-1.5">
                  {(["X", "Y", "Z"] as const).map((plane) => {
                    const visible = planeVisibility[plane];
                    return (
                      <button
                        key={plane}
                        type="button"
                        onClick={() => setPlaneVisibility((current) => ({ ...current, [plane]: !current[plane] }))}
                        aria-pressed={visible}
                        className="flex min-h-10 w-full items-center justify-between rounded-xl px-2.5 text-sm hover:bg-slate-100"
                      >
                        <span>المستوى {plane}</span>
                        {visible ? <Eye className="h-4 w-4 text-blue-600" /> : <EyeOff className="h-4 w-4 text-slate-400" />}
                      </button>
                    );
                  })}
                  <div className="my-2 border-t border-slate-200" />
                  {(["AB", "AC"] as const).map((line) => {
                    const visible = lineVisibility[line];
                    return (
                      <button
                        key={line}
                        type="button"
                        onClick={() => setLineVisibility((current) => ({ ...current, [line]: !current[line] }))}
                        aria-pressed={visible}
                        className="flex min-h-10 w-full items-center justify-between rounded-xl px-2.5 text-sm hover:bg-slate-100"
                      >
                        <span>المستقيم {line}</span>
                        {visible ? <Eye className="h-4 w-4 text-blue-600" /> : <EyeOff className="h-4 w-4 text-slate-400" />}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {!sceneError && (
              <div className={`pointer-events-none absolute bottom-3 left-1/2 z-10 -translate-x-1/2 rounded-full px-3 py-1.5 text-xs font-bold shadow-sm backdrop-blur transition ${interactionEnabled ? "bg-[#183A72]/90 text-white" : "bg-white/90 text-slate-600"}`}>
                {interactionEnabled ? "اسحب للتدوير • قرّب بإصبعين" : "اضغط زر اليد لتحريك المجسم"}
              </div>
            )}
          </div>

          <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs font-bold">
            <span className="text-blue-600">▰ المستوى X</span>
            <span className="text-red-600">▰ المستوى المنشأ Y</span>
            <span className="text-amber-700">▰ المستوى المفترض Z</span>
            <span className="text-red-700">━ AB</span>
            <span className="text-green-700">━ AC ⟂ X</span>
          </div>
          <p className="mt-2 text-xs text-slate-500">دوّر المستوى المفترض Z حول AB. لن يكون عمودياً على X إلا عندما يحتوي AC ويتطابق مع Y.</p>

          <div className="mt-4 grid gap-4 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2">
            <label className="block text-sm font-semibold">
              <span className="flex justify-between gap-2"><span>اتجاه المستقيم AB</span><b dir="ltr">{lineDirection}°</b></span>
              <input
                type="range"
                min={0}
                max={360}
                step={1}
                value={lineDirection}
                onChange={(event) => setLineDirection(Number(event.target.value))}
                className="mt-3 w-full accent-[#183A72]"
                aria-label="تغيير اتجاه المستقيم AB"
              />
            </label>
            <label className="block text-sm font-semibold">
              <span className="flex justify-between gap-2"><span>دوران المستوى المفترض Z حول AB</span><b dir="ltr">{candidateRotation}°</b></span>
              <input
                type="range"
                min={-75}
                max={75}
                step={1}
                value={candidateRotation}
                onChange={(event) => {
                  const next = Number(event.target.value);
                  setCandidateRotation(next);
                  if (next !== 0) setActiveStep((step) => Math.min(step, 2));
                }}
                className="mt-3 w-full accent-amber-600"
                aria-label="تدوير المستوى Z حول المستقيم AB"
              />
            </label>
          </div>

          <button
            type="button"
            onClick={() => setCandidateRotation(0)}
            className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#183A72] px-4 text-sm font-bold text-white transition hover:bg-[#102d5c]"
          >
            <Rotate3D className="h-4 w-4" />
            اختبر شرط التعامد
          </button>

          <div aria-live="polite" className={`mt-4 rounded-2xl border p-4 ${uniquePlaneConfirmed ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}>
            <p className="text-sm">
              زاوية Z مع X = <strong dir="ltr">{geometry.candidateAngleWithX.toFixed(1)}°</strong>
              <span className="mx-2">•</span>
              بُعد C عن Z = <strong dir="ltr">{geometry.distanceCToCandidate.toFixed(2)}</strong>
            </p>
            <p className="mt-2 text-sm font-bold">
              {uniquePlaneConfirmed
                ? "✓ Z ⟂ X ويحتوي AC؛ لذلك يتطابق Z مع Y، ولا يوجد مستوى عمودي آخر يحوي AB."
                : "✕ المستوى Z يحوي AB، لكنه لا يحتوي AC ولا يكون عمودياً على X؛ لذلك لا يحقق شروط المبرهنة."}
            </p>
          </div>
        </div>

        <aside className="rounded-2xl border border-slate-200 p-4">
          <h3 className="font-bold text-[#183A72]">خطوات البرهان</h3>
          <div className="mt-3 flex flex-wrap gap-2" aria-label="اختيار خطوة البرهان">
            {PROOF_STEPS.map((_, index) => (
              <button
                key={index}
                type="button"
                onClick={() => chooseStep(index)}
                aria-pressed={activeStep === index}
                className={`rounded-xl px-3 py-2 text-xs font-bold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#183A72] ${activeStep === index ? "bg-[#183A72] text-white" : "bg-slate-100 hover:bg-slate-200"}`}
              >
                {index === PROOF_STEPS.length - 1 ? "النتيجة" : `الخطوة ${index + 1}`}
              </button>
            ))}
          </div>
          <ol className="mt-4 space-y-3" aria-live="polite">
            {PROOF_STEPS.slice(0, activeStep + 1).map((step, index) => (
              <li key={index} className="rounded-xl bg-slate-50 p-3 text-sm leading-7">
                <span className="ms-2 font-bold text-[#183A72]">{index + 1}.</span>{step}
              </li>
            ))}
          </ol>
          {activeStep < 0 && <p className="mt-4 text-sm text-slate-500">اضغط على الخطوة الأولى لبدء البرهان.</p>}
        </aside>
      </div>
    </section>
  );
}
