// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying MCP connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-subjects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SUBJECTS = [
  { id: "physics", en: "Physics", ar: "\u0627\u0644\u0641\u064A\u0632\u064A\u0627\u0621" },
  { id: "chemistry", en: "Chemistry", ar: "\u0627\u0644\u0643\u064A\u0645\u064A\u0627\u0621" },
  { id: "biology", en: "Biology", ar: "\u0627\u0644\u0623\u062D\u064A\u0627\u0621" },
  { id: "english", en: "English", ar: "\u0627\u0644\u0625\u0646\u062C\u0644\u064A\u0632\u064A\u0629" },
  { id: "french", en: "French", ar: "\u0627\u0644\u0641\u0631\u0646\u0633\u064A\u0629" },
  { id: "arabic", en: "Arabic", ar: "\u0627\u0644\u0639\u0631\u0628\u064A\u0629" },
  { id: "islamic", en: "Islamic Education", ar: "\u0627\u0644\u062A\u0631\u0628\u064A\u0629 \u0627\u0644\u0625\u0633\u0644\u0627\u0645\u064A\u0629" }
];
var list_subjects_default = defineTool2({
  name: "list_subjects",
  title: "List subjects",
  description: "List all study subjects available in the app.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SUBJECTS, null, 2) }],
    structuredContent: { subjects: SUBJECTS }
  })
});

// src/lib/mcp/tools/list-chapters.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_chapters_default = defineTool3({
  name: "list_chapters",
  title: "List chapters for a subject",
  description: "List uploaded chapter folders available for a given subject.",
  inputSchema: {
    subject: z2.string().min(1).describe("Subject id, e.g. physics, chemistry, biology.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ subject }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.rpc("list_subject_chapters", { _subject: subject });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const chapters = (data ?? []).map((r) => r.chapter);
    return {
      content: [{ type: "text", text: JSON.stringify(chapters, null, 2) }],
      structuredContent: { subject, chapters }
    };
  }
});

// src/lib/mcp/tools/get-my-points.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_points_default = defineTool4({
  name: "get_my_points",
  title: "Get my points",
  description: "Get the total points the signed-in user has earned.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("user_points").select("points").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((s, r) => s + (r.points ?? 0), 0);
    return {
      content: [{ type: "text", text: `Total points: ${total}` }],
      structuredContent: { total, entries: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-my-todos.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_todos_default = defineTool5({
  name: "get_my_todos",
  title: "Get my todos",
  description: "Get the signed-in user's current todo list items.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("student_todos").select("items, updated_at, week_key").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = data?.items ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items, updated_at: data?.updated_at ?? null, week_key: data?.week_key ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mwksmqcthfwgvldgbggy";
var mcp_default = defineMcp({
  name: "tamyzak-mcp",
  title: "Tamyzak Study App",
  version: "0.1.0",
  instructions: "Tools for the Tamyzak study app. Use `list_subjects` and `list_chapters` to discover study material. Use `get_my_points` and `get_my_todos` to read the signed-in student's progress. Use `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_subjects_default, list_chapters_default, get_my_points_default, get_my_todos_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
