-- English Physics Chapter 2: Electromagnetic Induction (50 MCQs)
-- Idempotent by question text so repeated deployments do not duplicate the bank.
WITH seed (subject, chapter, chapter_title, section, language, question, choices, answer_index, source, sort_order) AS (
  VALUES
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic force on charged particles', 'en', 'A positively charged particle enters a uniform magnetic field with its velocity perpendicular to the magnetic flux density. According to the chapter, which combination correctly describes its motion?', '["Force parallel to velocity → straight-line acceleration","Force perpendicular to velocity → circular path","Force parallel to magnetic field → circular path","No magnetic force → constant straight-line motion"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 200),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic force on charged particles', 'en', 'The magnetic force acting on a charged particle moving in a uniform magnetic field reaches its maximum value when the angle between v and B is:', '["0^\\circ","30^\\circ","60^\\circ","90^\\circ"]'::jsonb, 3, 'Uploaded Chapter 2 MCQs', 201),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic force on charged particles', 'en', 'If the velocity vector of a charged particle becomes parallel to the magnetic flux density vector, the magnetic force becomes:', '["qvB","qB/v","Zero","Maximum"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 202),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic force on charged particles', 'en', 'Which set contains all the factors stated in the chapter as affecting the magnetic force on a charged particle?', '["q,\\;v,\\;B,\\;\\theta","q,\\;A,\\;B,\\;\\theta","q,\\;v,\\;A,\\;t","B,\\;A,\\;N,\\;R"]'::jsonb, 0, 'Uploaded Chapter 2 MCQs', 203),
  ('physics', 2, 'Electromagnetic Induction', 'Faraday experiments and induction', 'en', 'A magnetic rod remains stationary relative to a coil connected to an ammeter. The ammeter reads zero primarily because:', '["The magnetic flux through the coil is zero","The magnetic flux does not change with time","The magnetic rod has no magnetic field","The coil must contain an iron core"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 204),
  ('physics', 2, 'Electromagnetic Induction', 'Faraday experiments and induction', 'en', 'A magnetic rod and a coil move in the same direction with exactly the same velocity. According to the chapter, no induced current is produced because:', '["The magnetic flux is necessarily zero","The coil has no resistance","There is no relative motion and hence no change in magnetic flux through the coil","The magnetic field becomes parallel to the current"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 205),
  ('physics', 2, 'Electromagnetic Induction', 'Faraday experiments and induction', 'en', 'Which observation in Faraday’s primary–secondary coil experiment most directly demonstrates that a constant primary current does NOT continuously induce current in the secondary coil?', '["The secondary pointer deflects while the switch is being closed","The secondary pointer returns to zero after the primary current becomes constant","The secondary pointer deflects oppositely when the switch is opened","The primary circuit contains a battery"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 206),
  ('physics', 2, 'Electromagnetic Induction', 'Faraday experiments and induction', 'en', 'Faraday observed secondary current during which stages of the primary current?', '["Only while the primary current remained constant","Only during growth of primary current","Only during decay of primary current","During both growth and decay of primary current"]'::jsonb, 3, 'Uploaded Chapter 2 MCQs', 207),
  ('physics', 2, 'Electromagnetic Induction', 'Faraday experiments and induction', 'en', 'According to the chapter, the fundamental condition for generating induced current in a closed circuit is:', '["Presence of a permanent magnet","Presence of an iron core","Change in magnetic flux penetrating the circuit per unit time","Large constant magnetic flux"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 208),
  ('physics', 2, 'Electromagnetic Induction', 'Faraday experiments and induction', 'en', 'Why did attempts preceding Faraday’s discovery fail to generate electric current using magnetic fields?', '["They used alternating magnetic fields","They relied on constant magnetic fields","They used closed circuits","They used coils instead of straight conductors"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 209),
  ('physics', 2, 'Electromagnetic Induction', 'Faraday experiments and induction', 'en', 'Which modification can increase the induced current in a coil facing a moving magnetic rod according to the chapter?', '["Decreasing the number of turns","Decreasing the relative velocity","Inserting a wrought-iron core instead of air","Making the magnet and coil move together at the same velocity"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 210),
  ('physics', 2, 'Electromagnetic Induction', 'Faraday experiments and induction', 'en', 'A magnet is pushed toward a coil and then pulled away with the same speed. The induced currents in the two cases are:', '["Equal in direction because the speed is equal","Opposite in direction because the magnetic-flux change reverses","Zero because the net displacement is zero","Identical because the same magnet is used"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 211),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'In motional EMF, the charges in a conducting rod moving through a magnetic field accumulate at its ends because they are acted upon by:', '["Gravitational force","Magnetic force","Self-induced EMF","Eddy-current heating"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 212),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'For a rod moving perpendicular to a uniform magnetic field, which expression is given for motional EMF?', '["vB/\\ell","B\\ell/v","vB\\ell","v\\ell/B"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 213),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'According to the chapter, the motional EMF generated in a moving rod depends on:', '["B,\\;v,\\;\\ell only","B,\\;v,\\;\\ell,\\;\\theta","B,\\;A,\\;N only","I,\\;R,\\;N only"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 214),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'Maximum motional EMF occurs when the moving rod is:', '["Parallel to the magnetic flux","Perpendicular to the magnetic flux","Stationary inside the magnetic field","At 45^\\circ to the magnetic flux"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 215),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'If either the direction of motion of a rod OR the direction of the magnetic field is reversed, the chapter states that:', '["The magnitude and polarity of motional EMF remain unchanged","Motional EMF becomes zero","The polarity of motional EMF reverses","The length of the rod effectively changes"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 216),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'A conducting rod moves parallel to the magnetic field. Which statement is consistent with the chapter?', '["Motional EMF is maximum","Motional EMF is zero","Motional EMF equals vB\\ell","Motional EMF depends only on resistance"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 217),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'In the conductor-bar arrangement, the obstructive magnetic force acting on the rod is represented by:', '["F=B/I\\ell","F=I\\ell B","F=IB/\\ell","F=I\\ell/B"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 218),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'The obstructive force produced after induced current flows through a moving conductor acts:', '["In the same direction as the velocity","Opposite to the rod''s velocity","Parallel to the magnetic flux","Perpendicular to both velocity and magnetic field without affecting motion"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 219),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'In the conductor-bar system described in the chapter, constant velocity is maintained when:', '["Pulling force exceeds obstructive force","Obstructive force exceeds pulling force","Pulling force and obstructive force have equal magnitudes and opposite directions","Both forces act in the same direction"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 220),
  ('physics', 2, 'Electromagnetic Induction', 'Motional EMF', 'en', 'The work done in moving a conductor rod through a magnetic field is converted mainly into:', '["Magnetic potential energy only","Heat dissipated in the resistance","Gravitational potential energy","Mechanical energy stored permanently in the rod"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 221),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'Which of the following is NOT listed as one of the three fundamental quantities whose change can alter magnetic flux?', '["Magnetic flux density B","Surface area A","Angle \\theta","Circuit resistance R"]'::jsonb, 3, 'Uploaded Chapter 2 MCQs', 222),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'According to the chapter, magnetic flux through a surface is expressed as:', '["\\Phi_B=BA\\sin\\theta","\\Phi_B=BA\\cos\\theta","\\Phi_B=B/A","\\Phi_B=BA/\\cos\\theta"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 223),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'If the area vector of a ring is parallel to the magnetic flux density vector, the magnetic flux is:', '["Zero","Half its maximum value","Maximum","Independent of the area"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 224),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'When the plane of a conducting ring is parallel to the magnetic flux density vector, the chapter indicates that the magnetic flux through the ring is:', '["BA","BA/2","Zero","2BA"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 225),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'Faraday’s law states that the magnitude of induced EMF is directly proportional to:', '["Magnetic flux itself","Time interval alone","Time rate of change of magnetic flux","Resistance of the conductor"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 226),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'In Faraday’s law, the negative sign is included according to:', '["Ohm’s law","Lenz’s law","Coulomb’s law","The definition of magnetic flux"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 227),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'The polarity of the induced EMF depends on whether magnetic flux is:', '["Large or small","Uniform or nonuniform","Increasing or decreasing","Produced by a coil or magnet"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 228),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'A north magnetic pole approaches the face of a conducting ring. According to the chapter, the face of the ring behaves as:', '["A south pole to attract the magnet","A north pole to repel the approaching north pole","A neutral region","A south pole first and then a north pole"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 229),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'The same north pole is now moved away from the ring. The face of the ring becomes:', '["North, to repel the magnet","South, to attract the receding north pole","Magnetically neutral","Alternately north and south regardless of motion"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 230),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'The practical importance of Lenz’s law, as explicitly stated in the chapter, includes:', '["Calculating electrical resistance only","Determining the direction of induced current and demonstrating conservation of energy","Determining magnetic permeability only","Increasing generator speed"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 231),
  ('physics', 2, 'Electromagnetic Induction', 'Magnetic flux, Faraday and Lenz laws', 'en', 'Which best distinguishes external magnetic flux density B from induced magnetic flux density B_{ind}?', '["Both always act in the same direction","B is generated by induced current, while B_{ind} causes that current","A change in B causes induction, while B_{ind} opposes the change responsible for induction","B_{ind} exists before any induced current is produced"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 232),
  ('physics', 2, 'Electromagnetic Induction', 'Eddy currents', 'en', 'Eddy currents are described in the chapter as currents that are:', '["Straight and parallel to the magnetic field","Closed and circular in the conducting material","Present only in wires","Independent of electromagnetic induction"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 233),
  ('physics', 2, 'Electromagnetic Induction', 'Eddy currents', 'en', 'Eddy currents arise primarily as a consequence of:', '["Constant magnetic flux with no relative motion","Relative motion between a metal conductor and magnetic flux","Static electric charges","Constant current through an isolated resistor"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 234),
  ('physics', 2, 'Electromagnetic Induction', 'Eddy currents', 'en', 'The major disadvantage of eddy currents discussed in the chapter is:', '["Destruction of magnetic flux","Energy loss in the form of heat","Complete elimination of resistance","Prevention of electromagnetic induction"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 235),
  ('physics', 2, 'Electromagnetic Induction', 'Eddy currents', 'en', 'Why is an iron core divided into mutually insulated thin plates in transformers according to the chapter?', '["To decrease electrical resistance and increase eddy currents","To increase electrical resistance within the plates and reduce eddy currents","To eliminate magnetic flux density","To increase the thickness of current paths"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 236),
  ('physics', 2, 'Electromagnetic Induction', 'Eddy currents', 'en', 'In the pendulum experiment comparing a sliced and an unsliced conducting plate moving through a magnetic field, which plate stops sooner?', '["Sliced plate because it has smaller eddy currents","Unsliced plate because large eddy currents oppose its motion","Both stop simultaneously","Neither stops because eddy currents conserve mechanical motion"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 237),
  ('physics', 2, 'Electromagnetic Induction', 'Eddy currents', 'en', 'The vibration energy lost when the unsliced conducting plate eventually stops is transformed mainly into:', '["Electrical charge stored permanently on the plate","Heat energy due to eddy currents","Magnetic flux","Chemical energy"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 238),
  ('physics', 2, 'Electromagnetic Induction', 'Electric generators', 'en', 'Electric generators are described in the chapter as devices that convert:', '["Electric energy into mechanical energy","Mechanical energy into electric energy by the effect of a magnetic field","Thermal energy directly into magnetic energy","Magnetic energy into gravitational energy"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 239),
  ('physics', 2, 'Electromagnetic Induction', 'Electric generators', 'en', 'A single-phase AC generator contains which combination?', '["Coil, two magnetic poles, two sliding rings and two carbon brushes","Coil, commutator, one carbon brush and one magnetic pole","Three coils, commutator and no brushes","Coil, battery, resistor and galvanometer"]'::jsonb, 0, 'Uploaded Chapter 2 MCQs', 240),
  ('physics', 2, 'Electromagnetic Induction', 'Electric generators', 'en', 'During one complete rotation of a single-phase generator coil in a uniform magnetic field, the polarity of the induced EMF reverses:', '["Once","Twice","Three times","Four times"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 241),
  ('physics', 2, 'Electromagnetic Induction', 'Electric generators', 'en', 'According to the chapter, the induced EMF of a generator depends on all of the following EXCEPT:', '["Number of turns N","Area of one turn A","Magnetic flux density B","Resistance of the external circuit R"]'::jsonb, 3, 'Uploaded Chapter 2 MCQs', 242),
  ('physics', 2, 'Electromagnetic Induction', 'Electric generators', 'en', 'A three-phase AC generator consists of three coils separated by equal angles. The angular separation stated in the chapter is:', '["60^\\circ","90^\\circ","120^\\circ","180^\\circ"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 243),
  ('physics', 2, 'Electromagnetic Induction', 'Electric generators', 'en', 'The component that replaces the two sliding rings when constructing the DC generator described in the chapter is:', '["An iron core","A commutator consisting of two electrically isolated halves","A second coil","A galvanometer"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 244),
  ('physics', 2, 'Electromagnetic Induction', 'Electric generators', 'en', 'The average output current of the DC generator described in the chapter is related to its maximum current by:', '["I_{average}=I_{max}","I_{average}=0.636I_{max}","I_{average}=2I_{max}","I_{average}=0.5I_{max}"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 245),
  ('physics', 2, 'Electromagnetic Induction', 'Motors and back EMF', 'en', 'Why is the induced EMF generated in a rotating motor coil called “back EMF”?', '["It is always larger than the applied voltage","It acts in the same direction as the applied voltage","It opposes the EMF that generated the motor current according to Lenz’s law","It exists only after the motor stops"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 246),
  ('physics', 2, 'Electromagnetic Induction', 'Motors and back EMF', 'en', 'According to the motor relation given in the chapter, the current flowing through the motor is determined by:', '["I=\\dfrac{V_{applied}+E_{back}}{R}","I=\\dfrac{E_{back}-V_{applied}}{R}","I=\\dfrac{V_{applied}-E_{back}}{R}","I=R(V_{applied}-E_{back})"]'::jsonb, 2, 'Uploaded Chapter 2 MCQs', 247),
  ('physics', 2, 'Electromagnetic Induction', 'Self-induction', 'en', 'The coefficient of self-inductance of a coil depends on all of the following EXCEPT:', '["Size of the coil","Geometrical shape of the coil","Number of turns","Time rate of change of current through the coil"]'::jsonb, 3, 'Uploaded Chapter 2 MCQs', 248),
  ('physics', 2, 'Electromagnetic Induction', 'Mutual induction', 'en', 'Two adjacent closed coils are arranged so that current in the primary coil changes with time. According to mutual induction, an EMF appears in the secondary because:', '["The secondary resistance changes automatically","The changing primary current changes the magnetic flux penetrating the secondary coil","The secondary current must initially be constant","Both coils must carry identical currents"]'::jsonb, 1, 'Uploaded Chapter 2 MCQs', 249)
)
INSERT INTO public.mcq_banks (
  subject, chapter, chapter_title, section, language, question, choices, answer_index, source, sort_order
)
SELECT
  s.subject, s.chapter, s.chapter_title, s.section, s.language, s.question, s.choices, s.answer_index, s.source, s.sort_order
FROM seed AS s
WHERE NOT EXISTS (
  SELECT 1
  FROM public.mcq_banks AS existing
  WHERE existing.subject = s.subject
    AND existing.chapter = s.chapter
    AND existing.language = s.language
    AND existing.question = s.question
);
